//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBC_ComOnline
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBC_ComOnlineEntities1 : DbContext
    {
        public BBC_ComOnlineEntities1()
            : base("name=BBC_ComOnlineEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articuloes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Articulo_Proveedor> Articulo_Proveedor { get; set; }
        public virtual DbSet<Empresa_Articulo> Empresa_Articulo { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Usuario_Personal> Usuario_Personal { get; set; }
        public virtual DbSet<Modulo> Moduloes { get; set; }
        public virtual DbSet<Cargo_Modulo> Cargo_Modulo { get; set; }
        public virtual DbSet<Unidad_Medida> Unidad_Medida { get; set; }
        public virtual DbSet<Venta> VentaSet { get; set; }
        public virtual DbSet<Detalle_Venta> Detalle_VentaSet { get; set; }
        public virtual DbSet<Detalle_Carro> Detalle_CarroSet { get; set; }
        public virtual DbSet<Carro_Compra> Carro_CompraSet { get; set; }
        public virtual DbSet<Caja> CajaSet { get; set; }
    }
}
